spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&charactorEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    prefix: classpath:/static
    suffix: .html
  mvc:
    view:
      prefix: classpath:/static
logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log








