server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&charactorEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/
  thymeleaf:
    prefix: classpath:/static
    suffix: .html
  mvc:
    view:
      prefix: classpath:/static
  redis:
    host: localhost
    password:
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: springboot-session
logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log
